### PR TITLE
Tank heating control board

### PR DESCRIPTION
**Pull request by JasonBrave**
ready to review

### CODE REVIEW

**Comment by Artem-Sotnikov** [comment]
Overall, schematic seems straightforward and reasonable to me. I would however throw on some always-on LEDs: one in parallel with the output as a quality-of-life feature would be nice.

**Review by Artem-Sotnikov — APPROVED** [review]

**Review by zx100x100 — CHANGES_REQUESTED** [review]
Important to remember: nominal voltage for the system is 24V, but max voltage for the system is 28.8V (2 car batteries fully charged in series). as such:

- voltage sensing dividers need to be adjusted
- current sensing must be done on the low side, as 28.8V is above the max high side voltage for the INA180

otherwise nothing jumps out as a problem, but I didn't have a ton of time to check

**Review by Joe-Joe-Joe-Joe — APPROVED** [review]
Kicad 8 cringe
Schematic looks good to me, aside from what Zach identified

**Comment by zx100x100** [comment]
Please add silkscreen labels for the pinout of the screw terminals. you should not need to reference the PCB design to determine the pinout. 

Your ground plane is a bit of a chopped up mess. you either need to carefully stitch it to avoid these wild ground loops, or make the board 4 layers.
image

Please include gerbers in next commit.

A note for the future: a couple of your part placement choices are strange, mostly you place the two resistors of a divider far from each other, which isn't wrong, but a bit less clear. No worries as this was a rushed design

**Pull request merged**
