### PR TITLE
Powerboard shield layout and routing

### PR DESCRIPTION
**Pull request by MattiGen**
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/rlcs/26)

### CODE REVIEW

**Comment by AidanHa** [comment]
My late review:

It seems like there are merge conflicts (when there shouldn't be), maybe look into them to see if its nothing serious

You got some silkscreen overlap at TP3
image

c1-c4 look  dangerously close to t1 and T2
image

maybe put some more space between t1 and r2, the r2 silkscreen might be a bit blocked
image

I kinda want the silkscreen of the Waterloo Rocketry logo to be on the front, and you have some extra space below c3 and c4, so if you want, you could move it. You can also choose a smaller silk screen if it doesnt fit (we should like like 3 different logo sizes, but you might have to export them from the canlib library
image

otherwise, feel free to start your routing

**Comment by AidanHa** [comment]
My review:

Still some merge conflicts, hopefully nothing troublesome.

The 12V trace at F1 seems to be a bit skinny, try making it 0.4mm (or actually make it 1mm). Not too sure what it says in the electrical standards.
image

I'm not a fat of having vias directly on top of a solder pad (p1 of R16 and R15). Not too sure if there's anything in the electrical manual about this (and can't remember if it actually correct to do this). Could you move the vias off the pads?
image

Please redo the connection for the VDD pad of J1. Let's assume for some reason, the VDD pad fails (someone burned it with a solder iron or idk). Then it would affect the rest of the connection attached to the pad. I have 2 pictures below. The first one is what you are currently doing, and the second one is what I would like you to do (it might make sense in the picture)

What you are doing:
image

What I want:
image

Hopefully you see how the connections to R18 and r15 arent daisy chained to the VDD pad of J1.

More vias on top of pads, which i don't like:
image

You got 2 TP3, Is that intentional?
image


The one trace at the lower right out edge is cutting really close to the edge. I was suggest you increase the area of the space that trace has by increasing the size of the board (edge cuts). As long as the arduino connectors are in the right location, then the size of the board doesn't really matter
image


inconsistency of size with the 12V trace at T1
image

Feels like the trace sizes are a bit inconsistent (you switch from o.254mm to 0.4mm). I think for all the lines that aren't the 12v line, you should choose a width and stick with it.

Feels like the traces are a little too close for comfort. It should be fine, but if you could shift each trace a little bit more to the middle, then that would be nice.
image


Everything else looks fine. Keep up the good work and make sure you decide a name for the board!

**Comment by AidanHa** [comment]
Review round 2:

got a DRC problem here:
image
not sure if you got the same problem, but run DRC again just to double check.

Ard_con_sd__scl trace might be too close to tp 2
image

No idea if its me but seems like the 12V trace isn't properly connected to TP1. DRC doesn't return an error, so might be fine
image

Silkscreen popping out for s1
image

Nothing major, good work! Feel free to generate gerbers on your next commit. Will try to get more people to review the board.

**Review by zx100x100 — CHANGES_REQUESTED** [review]
Love the overall look, a few things

I believe the SPI pinout is wrong, MISO looks like it should be pin 50, and I believe SCK (For SPI) should be 52. Also right now you have the SD card SPI clock set as the I2C clk not SPI! currently  the board won't work.

The reset button is currently some little SMD jobbie, would be ideal to make it a standard 4 pin through-hole button that we already have a bunch of.

Also currently there is no silk screen label on any of the connectors, at minimum please add the pinout for the non-arduino connectors, but I would also really prefer you add the arduino connector pinouts as otherwise it will be a pain to do any field work with the board.

finally there are a whole bunch of instances of daisy chaining through pads. the 12V rail is probably the worst culprit, but please review all the routing as there are also a few on the 5V rail, and maybe a couple others.

**Comment by zx100x100** [comment]
Missed it last night but the I2C lines need pull up resistors to function correctly, and since this board is essentially the master they should be on this board.

4.7k is probably a good value

**Comment by AidanHa** [comment]
New changes look fine. Maybe wait for Zach to give them a quick look before you create  the gerbers

**Review by zx100x100 — COMMENTED** [review]
Looks good! my only thing is can you finish labeling the pins where there is space? 
I don't mind not labling pins where there just isn't space to, but it kind of bothers me having missing labels where there is space. This includes using the small bit of space under the two row connector to add a couple numbers on that side.

image

Also could you please label the voltage on the test points (and the ground test point as ground)

Overall I like the routing and I think you can include gerbers in the next commit.

**Review by zx100x100 — APPROVED** [review]
Looks Good! :fantasticstuff: :partyparrot:

**Comment by ZTeper** [comment]
-Check whether the Arduino-SD-MISO connection should be translated from 5V to 3V3.
-You are using 100 Ohm resistors for the LEDs in the 7-segment display. That resistance seems a bit small. I would recommend 150 to 200 Ohm resistors.
-For Q1 and Q2, consider adding a 10kOhm resistor to the base of each transistor, in order to limit the current flowing into the base.

**Comment by MattiGen** [comment]
> -Check whether the Arduino-SD-MISO connection should be translated from 5V to 3V3.
Its 5V
> -You are using 100 Ohm resistors for the LEDs in the 7-segment display. That resistance seems a bit small. I would recommend 150 to 200 Ohm resistors.
For the 7-segment LEDs they can handle more flow than your typical red LED so 100 is fine.
> -For Q1 and Q2, consider adding a 10kOhm resistor to the base of each transistor, in order to limit the current flowing into the base.
In my experience this isn't neccesary, @zx100x100 your thoughts?

**Comment by zx100x100** [comment]
10K is excessive, I've seen like 270 ohms to limit transient current but since MOSFETS don't draw current on the base at steady state they aren't necessary (Unlike BJTs)

**Review by QuantumManiac — APPROVED** [review]
Sorry for the delay. Looks good to me!

**Pull request merged**
