### PR TITLE
Add voltage sensing, fix transistor footprint and redo shield

### PR DESCRIPTION
**Pull request by BluCodeGH**
Note: This board is critical for SF6, please review ASAP!

---
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/rlcs/30)

### CODE REVIEW

**Comment by ZTeper** [comment]
Please add current limiting resistors to the bases of Q1 and Q2.
Please add a pdf of the schematic. #

**Review by ZTeper — CHANGES_REQUESTED** [review]
https://github.com/waterloo-rocketry/rlcs/pull/30#issuecomment-1023719001

**Review by QuantumManiac — CHANGES_REQUESTED** [review]
**Schematic:**
- Could make the layout of the labelling for resistors consistent between all of them (e.g. make all of them have the resistor value inside the "resistor box" vs beside it). Doesn't matter to the `R_Small` symbols ofc

- Move this sheet up so stuff doesn't touch the border:
image

- There's plenty of empty space if you want to spread these out a bit more for readability
image

- Not lined up, smh:
image

**Board:**
- LGTM
- Add board and hole spacing dimensions pls

**Review by ZTeper — APPROVED** [review]

**Review by rdakhil — APPROVED** [review]
LGTM, just some minor non-critical suggestions:
- might be good to indicate the current rating on F1, also the voltage range of actuator_bat
- place some NC flags on the unconnected Arduino pins to make ERC happier

**Review by QuantumManiac — APPROVED** [review]
Schematic
- Nit: `R1` and `R12` have their RefDes above the symbol while every other one has it below.  
- Nit: Could update the title block if desired. 

Board:
- LGTM

**Review by jlsajfj — APPROVED** [review]
lgtm

**Comment by BluCodeGH** [comment]
Ordered, merging.

**Pull request merged**
