### PR TITLE
Client-side board

### PR DESCRIPTION
**Pull request by JasonBrave**
RLCS Client-side board schematic, Arduino GPIO pin usage are subject to change

- - -
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/rlcs/41)

### CODE REVIEW

**Comment by kfdliu** [comment]
Seems legit to me.

**Review by kfdliu — APPROVED** [review]

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
Looks good overall, some issues I spotted:

1. Keylock switch ground should just actually go to ground not an arduino pin.
2.  The UART screw terminal needs to provide power and ground too.
3. Typically the team uses US-style resistors (squiggles) vs EU style (boxes).
4. Small-valued resistors (eg 100 ohms) should have a R suffix, so 100R not just 100.
5. The current missile switch control circuitry either connects it to +5V or has it effectively NC, so this won't work as a current sink to ground like it needs to. You should use a single mosfet in a low-side switching configuration, see "Aaron explains mosfets" pinned message in #electrical.
6. Generally this schematic would be a lot more clear with some more subsheets, eg power and switches.
7. I've had issues with A0 on arduino's, I'd move 12V_SENSE to A1.

**Comment by BluCodeGH** [comment]
Oh we should also move the MV5 through MV8 connections to the currently unused digital i/o pins rather than having them on the serial pins since that's kinda sus. Also here is Aaron's screenshot for the correct switch LED control circuit
image

**Review by BluCodeGH — APPROVED** [review]
Schematic LGTM, although you should rename the kicad project to just "clientside board" since the actual kicad project has both the schematics and the PCB lol.

**Review by QuantumManiac — APPROVED** [review]
Looks good to move to the next step! Agree with Jack on renaming the project folder

**Review by eliaskountouris — APPROVED** [review]

**Comment by JasonBrave** [comment]
Layout updated

**Review by BluCodeGH — APPROVED** [review]
Layout looks great, you should be good to proceed with routing. Some tweaks to make:

1. Is 5A the correct size for that fuse? Sounds a bit large.
2. The mounting holes (arduino and LCD) should be plated so the screws don't dig into the fiberglass.
3. Are those screw terminals going to block us plugging a usb cable into the arduino? We are going to want to use the USB port on clientside at comp (to feed data into omnibus) so there needs to be space for a cable there.
4. This is entirely a "jack likes pretty boards" point but imo its nice to make things aligned and evenly spaced. The positions of the screw terminals on the left side in particular look a bit chaotic. Likewise I'd try to be consistent with how I'm positioning the pull-down resistors with respect to their screw terminals.
5. You can probably tighten things up a bit by moving the pulldown resistors to be next to the arduino pins and "under" the arduino, and by moving the bit of circuitry on the right of the arduino to under it as well.
6. Using the 3.5mm pitch is understandable for the missile switch connections but generally 5mm / 5.08mm are much nicer to work with so I'd prefer we stick with that size for everything else (UART, LED, pot, etc).

**Comment by JasonBrave** [comment]
Added PCB routing and silkscreen

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
:heart_eyes: pretty board! The usual bunch of small things to fix:

1. +12V input screw terminal is backwards
2. Rounded corners make me unreasonably happy, all it takes is a .1" radius which you should be able to fit no problem
3. Technically the +12V trace is daisy chained through C1. I think you can avoid that dip left of the regulator by moving C1 out of the way, routing straight to the regulator, and then putting C1 back somewhere reasonable.
4. When you're using a capacitor to reduce noise, C2 for example, then both the positive and negative paths will affect its performance. Here you have a great positive path (ie very short trace between the regulator output and C2) but the "return path" (ground) goes all the way over to the ground test point and then all the way back along the back of the PCB before it makes it to ground on the regulator. Instead you should drop a via right next to the ground side of C2 to make that path as short as possible.
5. The same situation with wanting short returns paths applies elsewhere. If you take a look at the GND net you have this big trace on the front of the board that connects the pull down resistors, missile switch light FET, and only after a very long distance makes it to your actual ground plane via the arduino through-holes. Instead you should have an individual via to ground for each resistor, the FET, etc. Vias are free, use them! (This also would remove all the daisy chaining you have going on with that line).
6. You've got a right angle in the trace between R6 and R7. Supposedly doesn't matter much these days but 45 degree intersections look nice.
7. That LCD contrast trace is cutting your ground pour in half. I'd move like 1" of it onto the top of the PCB with vias to give better ground connections.
8. I know I said to move it back earlier but looking at it now we should probably keep Q1 on the right side of the PCB so it's close to the screw terminal connector. If we want to give each LED ~10 mA that line will be seeing a not-entirely-negligible amount of current, so best to keep it short and maybe a bit thicker. Also I know the old design didn't have one but it's probably smart to add a current limiting resistor, you should measure the voltage drop across those switches and size a resistor accordingly.
9. Reminder to add the standard team logo + board name + your name + date silkscreen.

**Review by BluCodeGH — APPROVED** [review]
Looks great! Two tiny things:
- Your silkscreen labels on the RGB LED connector will be obscured by the wires, you should move them to the other side of the screw terminal.
- We should also add mounting holes for this board itself to get mounted to the plywood of clientside.

**Review by QuantumManiac — APPROVED** [review]
LGTM! Agree with Jack's points above. `R1`-`R3` looks to be easily movable to fit the RGB LED labels where they should be.

Also, re-plotting the schematic PDFs would be appreciated, as they look to be out-of-date.

**Review by rdakhil — APPROVED** [review]
C1 should be placed closer to the DC-DC converter module input pin (specified in datasheet, "Note 1"). Otherwise, LGTM!

**Review by DomenicHampson — APPROVED** [review]
LGTM!

**Comment by Artem-Sotnikov** [comment]
Overall looks good, but I agree with the silkscreen nitpicks from earlier (RBGs being blocked by wires) and have a few of my own nitpicks as well. The silkscreen on T1 will probably be unreadable after the module is placed upon it. 

image

Similarly, the area here seems ripe for possible confusion.

image

I would suggest mucking about with the silkscreen text here in order to make it easier to read:

image

The last and most nitpicky of all is the fact that the fuse traces seem excessively wide for a 1A current on a surface layer and will probably be more of a hassle if ever it must be desoldered due to the massive thermal contact they'll be experiencing. Considering the diligent application of thermal protection elsewhere on the board, this will probably be the most annoying part to desolder. But this is so far down the hierarchy of needs that it might be irrelevant, idk.

image

Anyway I still want to review HILT today so I'll leave it at that, board should be fine to order even without any changes if we don't have the time to make them.

**Comment by JasonBrave** [comment]
@BluCodeGH Silkscreen fixed, I cannot fit a mounting hole at bottom-right corner
@QuantumManiac Fixed
@rdakhil Fixed. Does it have to be even closer? E.g. make the capacitor pad and trace overlap?
@Artem-Sotnikov Silkscreen fixed, fuse trace will be fixed in a future commit

**Comment by BluCodeGH** [comment]
Ordered, merging.

**Pull request merged**
