### PR TITLE
Client v3

### PR DESCRIPTION
**Pull request by zx100x100**
PR to review code changes for SF

---
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/rlcs/25)

### CODE REVIEW

**Comment by jacobdeery** [comment]
Can you add a bit of context in your description as to what the new features/major changes are? An 800/450 LOC diff across 22 files is not the easiest to comprehend in a glance.

**Comment by zx100x100** [comment]
the overall purpose of this PR is to rename a lot of things so that the code now refers to valves by generic numbers, instead of specific functions. this means the system is much more easily used for different P&IDs.

it also includes some code changes to the client side code that are needed for the V3 box, including software arming, and LED control.

overall this code base is a bit of a garbage fire, I'm sure that there are things that should be fixed specific to the PR, but there is also a lot that should be cleaned up that falls outside of the scope of this PR. I'd like to get it merged so that master actually works with our systems.

**Review by dwkletke — COMMENTED** [review]
Most of my comments are whitespace related. Seems like most of the changes were pretty straightforward! 

> Reviewed 3 of 7 files at r1, 1 of 2 files at r3, 18 of 18 files at r5.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/rlcs/25#-:-MOx2XPb8BCldWz4PQLd:b7uaus)* status: all files reviewed, 19 unresolved discussions (waiting on @AidanHa, @jacobdeery, @JaredWatson, and @zx100x100)

___
*[src/client_arduino_ide/client_arduino_ide.ino, line 39 at r5](https://reviewable.io/reviews/waterloo-rocketry/rlcs/25#-MOwz6mi98q5u1RSmFCp:-MOwz6mjATRxy6oEMF9V:b-cogb0h) ([raw file](https://github.com/waterloo-rocketry/rlcs/blob/50a82931e47065731ef0889279c12f8b9aae1399/src/client_arduino_ide/client_arduino_ide.ino#L39)):*
> ```
> ··
> ```
Extra whitespace :)
___
*[src/client_arduino_ide/client_globals.c, line 31 at r5](https://reviewable.io/reviews/waterloo-rocketry/rlcs/25#-MOwzNA3DOq_WeAtY4KH:-MOwzNA3DOq_WeAtY4KI:b-grtl0w) ([raw file](https://github.com/waterloo-rocketry/rlcs/blob/50a82931e47065731ef0889279c12f8b9aae1399/src/client_arduino_ide/client_globals.c#L31)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>     button_t valve_1;
>     button_t valve_2;
>     button_t valve_3;
>     button_t valve_4;
> ```
</details>

Now that these were changed to `valve_#`, is there going to be any indication for what each valve does somewhere else in the code? Was there a reason to why these were generalized? Does each specific valve now serve more than one purpose?
___
*[src/client_arduino_ide/client_globals.c, line 187 at r5](https://reviewable.io/reviews/waterloo-rocketry/rlcs/25#-MOx-ZMnDuXeCmSCg_mz:-MOx-ZMo2SQT9lp_t5g6:b-w2w62q) ([raw file](https://github.com/waterloo-rocketry/rlcs/blob/50a82931e47065731ef0889279c12f8b9aae1399/src/client_arduino_ide/client_globals.c#L187)):*
> ```
> ····
> ```
Extra whitespace.
___
*[src/client_arduino_ide/client_globals.c, line 228 at r5](https://reviewable.io/reviews/waterloo-rocketry/rlcs/25#-MOx-dKP25zorda_hWY3:-MOx-dKP25zorda_hWY4:b-xcj9ia) ([raw file](https://github.com/waterloo-rocketry/rlcs/blob/50a82931e47065731ef0889279c12f8b9aae1399/src/client_arduino_ide/client_globals.c#L228)):*
> ```
> ··
> ```
Extra whitespace.
___
*[src/client_arduino_ide/LCD.cpp, line 88 at r5](https://reviewable.io/reviews/waterloo-rocketry/rlcs/25#-MOx00Na2PW7puKV4bi1:-MOx00Na2PW7puKV4bi2:b-pgmsqu) ([raw file](https://github.com/waterloo-rocketry/rlcs/blob/50a82931e47065731ef0889279c12f8b9aae1399/src/client_arduino_ide/LCD.cpp#L88)):*
> ```
> //static bool display_first_line = false; // changed to false per my evil scemes mentioned below.
> ```
Should this be removed since it is commented out? Is it going to be needed again?
___
*[src/client_arduino_ide/LCD.cpp, line 90 at r5](https://reviewable.io/reviews/waterloo-rocketry/rlcs/25#-MOx0-Iz4smbDzJ7zd-l:-MOx0-Iz4smbDzJ7zd-m:btz9vnz) ([raw file](https://github.com/waterloo-rocketry/rlcs/blob/50a82931e47065731ef0889279c12f8b9aae1399/src/client_arduino_ide/LCD.cpp#L90)):*
> ```
> //static long time_last_line_switch = 0;
> ```
Same here.
___
*[src/client_arduino_ide/LCD.cpp, line 93 at r5](https://reviewable.io/reviews/waterloo-rocketry/rlcs/25#-MOx09NJ1uuvlv5fFx5D:-MOx09NJ1uuvlv5fFx5E:bomer9t) ([raw file](https://github.com/waterloo-rocketry/rlcs/blob/50a82931e47065731ef0889279c12f8b9aae1399/src/client_arduino_ide/LCD.cpp#L93)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
> /*                                            // I have hijacked these lines so I can always see what the state of the valve connected to disconnect is. Bwa ha ha ha ha!
>     if (millis() - time_last_line_switch > 2000) {
>         display_first_line = !display_first_line;
>         time_last_line_switch = millis();
>     }
> */
> ```
</details>

Same question here.
___
*[src/client_arduino_ide/LCD.cpp, line 126 at r5](https://reviewable.io/reviews/waterloo-rocketry/rlcs/25#-MOx0Jck8lJZ469R7RK2:-MOx0Jck8lJZ469R7RK3:b-bfuwg8) ([raw file](https://github.com/waterloo-rocketry/rlcs/blob/50a82931e47065731ef0889279c12f8b9aae1399/src/client_arduino_ide/LCD.cpp#L126)):*
> ```
> ····
> ```
Some extra whitespace.
___
*[src/client_arduino_ide/shared_types.h, line 50 at r5](https://reviewable.io/reviews/waterloo-rocketry/rlcs/25#-MOx1JaS8eWUiGgcbEG3:-MOx1JaS8eWUiGgcbEG4:b-bqoyk2) ([raw file](https://github.com/waterloo-rocketry/rlcs/blob/50a82931e47065731ef0889279c12f8b9aae1399/src/client_arduino_ide/shared_types.h#L50)):*
> ```
> ····
> ```
Extra whitespace here.
___
*[src/tower_arduino_ide/tower_arduino_ide.ino, line 84 at r5](https://reviewable.io/reviews/waterloo-rocketry/rlcs/25#-MOx1bUn7mbvjcoIybG2:-MOx1bUn7mbvjcoIybG3:bnhogks) ([raw file](https://github.com/waterloo-rocketry/rlcs/blob/50a82931e47065731ef0889279c12f8b9aae1399/src/tower_arduino_ide/tower_arduino_ide.ino#L84)):*
> ```
> // DEPRECATED: setNewNum_SevSeg( (uint8_t) fromBase64(to_put_on_sevenseg) );
> ```
Can this be deleted if it is deprecated?
___
*[src/tower_arduino_ide/tower_daq.c, line 54 at r5](https://reviewable.io/reviews/waterloo-rocketry/rlcs/25#-MOx1mRi4Y3ULQIoGtHp:-MOx1mRi4Y3ULQIoGtHq:b-w2w62q) ([raw file](https://github.com/waterloo-rocketry/rlcs/blob/50a82931e47065731ef0889279c12f8b9aae1399/src/tower_arduino_ide/tower_daq.c#L54)):*
> ```
> ····
> ```
Extra whitespace.
___
*[src/tower_arduino_ide/tower_daq.c, line 98 at r5](https://reviewable.io/reviews/waterloo-rocketry/rlcs/25#-MOx1omOBzommeRbklpC:-MOx1omOBzommeRbklpD:b-w2w62q) ([raw file](https://github.com/waterloo-rocketry/rlcs/blob/50a82931e47065731ef0889279c12f8b9aae1399/src/tower_arduino_ide/tower_daq.c#L98)):*
> ```
> ····
> ```
Extra whitespace.
___
*[src/tower_arduino_ide/tower_daq.c, line 128 at r5](https://reviewable.io/reviews/waterloo-rocketry/rlcs/25#-MOx1pfn1JsyWouHq9aC:-MOx1pfn1JsyWouHq9aD:bz64yv2) ([raw file](https://github.com/waterloo-rocketry/rlcs/blob/50a82931e47065731ef0889279c12f8b9aae1399/src/tower_arduino_ide/tower_daq.c#L128)):*
> ```
> ········
> ```
Extra whitespace.
___
*[src/tower_arduino_ide/tower_daq.c, line 184 at r5](https://reviewable.io/reviews/waterloo-rocketry/rlcs/25#-MOx1r_n2xb9PC4_Wzfg:-MOx1r_n2xb9PC4_Wzfh:b-w2w62q) ([raw file](https://github.com/waterloo-rocketry/rlcs/blob/50a82931e47065731ef0889279c12f8b9aae1399/src/tower_arduino_ide/tower_daq.c#L184)):*
> ```
> ····
> ```
Extra whitespace.
___
*[src/tower_arduino_ide/tower_globals.c, line 115 at r5](https://reviewable.io/reviews/waterloo-rocketry/rlcs/25#-MOx20i8-zFq9VpNLyKT:-MOx20i8-zFq9VpNLyKU:bz64yv2) ([raw file](https://github.com/waterloo-rocketry/rlcs/blob/50a82931e47065731ef0889279c12f8b9aae1399/src/tower_arduino_ide/tower_globals.c#L115)):*
> ```
> ········
> ```
Extra whitespace.
___
*[src/tower_arduino_ide/tower_globals.c, line 122 at r5](https://reviewable.io/reviews/waterloo-rocketry/rlcs/25#-MOx21krEIA1Fdr4gSRx:-MOx21ks-uCBSyDrkPSD:bz64yv2) ([raw file](https://github.com/waterloo-rocketry/rlcs/blob/50a82931e47065731ef0889279c12f8b9aae1399/src/tower_arduino_ide/tower_globals.c#L122)):*
> ```
> ········
> ```
Extra whitespace.
___
*[src/tower_arduino_ide/tower_globals.c, line 177 at r5](https://reviewable.io/reviews/waterloo-rocketry/rlcs/25#-MOx24WZ7UWf8o5tH4aj:-MOx24WZ7UWf8o5tH4ak:b-w2w62q) ([raw file](https://github.com/waterloo-rocketry/rlcs/blob/50a82931e47065731ef0889279c12f8b9aae1399/src/tower_arduino_ide/tower_globals.c#L177)):*
> ```
> ····
> ```
Extra whitespace.
___
*[src/tower_arduino_ide/tower_globals.c, line 185 at r5](https://reviewable.io/reviews/waterloo-rocketry/rlcs/25#-MOx25Pb2qwjl0VwbZLE:-MOx25Pb2qwjl0VwbZLF:b-w2w62q) ([raw file](https://github.com/waterloo-rocketry/rlcs/blob/50a82931e47065731ef0889279c12f8b9aae1399/src/tower_arduino_ide/tower_globals.c#L185)):*
> ```
> ····
> ```
Extra whitespace.
___
*[src/tower_arduino_ide/tower_globals.c, line 191 at r5](https://reviewable.io/reviews/waterloo-rocketry/rlcs/25#-MOx26HL8Siwmu_49vCo:-MOx26HMEAvegJXr63pl:b-w2w62q) ([raw file](https://github.com/waterloo-rocketry/rlcs/blob/50a82931e47065731ef0889279c12f8b9aae1399/src/tower_arduino_ide/tower_globals.c#L191)):*
> ```
> ····
> ```
Extra whitespace.

**Comment by LanaTomlin** [comment]
Gonna say that I think this should be merged to master no matter what - the code works and has been used for several SF attempts, but I'm gonna make a list of things that should probably be addressed in the future. Maybe some things to make issues out of.

1. tower_arduino_ide
Why is convert_state_to_radio missing so that we can't display things? We should probably be adding that back in, no?
should be more specific in comments then "deal with nodeio.ioio stuff". What is?? the nodeio.ioio stuff??
maybe replace "//not a thing right now" with "not relevant to static fire testing"
probably would be better practice to define a macro at the top of the file which turns on/off certain features based on what kind of test we're running. 

just gonna put this comment here:
    //run tank valve
    //TODO, figure out how the run tank valve is going to work
    //likely involve a serial link to another arduino
    //I don't think this should be here, we have RocketCAN - Zach 2020-02-20
should probably make that an issue

The comment on init_outputs(); should be:
//set pins to output
//set all valves to safe states
//run tank valve - TO DO 
//Initialize LINAC
//Set ignition off

TO DO:
use a nother macro to turn LINIC on and off, everything in the linac_init() function in linac.c is currently commented out

Why are default states being set in both nio_init() and init_outputs()?? doesn't make sense to me, feels very frankenstien codey. (which is honnestly all of my code so who am i to criticize)

WOW I REALLY SHOULD'VE USED MORE FORMATTING TO MAKE THIS EASIER TO READ

TOO LATE, my apologies. she says while continuing the chaotic comment

What is flush. it's used so much, but i have no idea what it does. does it flush the buffer onto the SD card? does it deleted the contents of a file on the SD card? I don't know. I guess I could read the function instead of skim it but im tired, im sorry


2. linac.c
WHAT THE ACUTAL FUCK ARE THESE COMMENTS THEY SOUND LIKE I WROTE THEM
#define LINAC_POWERED_TIME_MOVING 2000 // who needs duty cycling time anyways
#define LINAC_UNPOWERED_TIME_MOVING 50
//turn on and off this many times while moving
#define LINAC_CYCLES_MOVING 1 // lets do it all in one go
//don't move for 2 seconds after moving
#define LINAC_COOLDOWN_TIME 50 // cooldown time? where we're going we don't need cooldown time

i have so many questions. so, so many questions.  (mainly what? who? why? and what the fuck does this timing shit do?)

we whould really be skipping out the function calls to linac.c using a macro instead of just....commenting out the body of the whole ass function

3. tower_daq.c
Please be a bit more desciptive as to what a window holder is in the init_daq_pins function
"memset"?? Is some sort of memory thing by a quick google search. I don't understand that shit.

nodeio.ioio
void nio_init()
//Set default values for LCD
//Initialize UART at 9600 baud for radio - maybe that shoudl be another macro as well??
//Set default injector and vent valve states


4.sd_handler.cpp
there is no error thrown when rlcs log isn't working
you print to serial when the SD card can't be found. there ain't no serial in the tower side box. that should either go on the seven segment boi or blink. some leds, i think. 

WHAT THE FUCK
WHAT THE FUCK 
I AM TIRED AND THE SCreen is so bright and it hurts my eyes and i dont understand this code in the *slighest*
        while(true){
            File s = output_log.openNextFile();
            if(s.isDirectory()){
#ifdef SD_SERIAL_LOG
                Serial.println("found another directory");
                Serial.flush();
#endif
                s.close();
                continue;
            }
oh im guessing that just yeets out a bunch of dierectories???? hmmm i dont understand continues 

            if(!s){ - great variable name. fantatstic. so totally tells me so much about how what this if statement does. very good. (this is sacrasm what the fuck is 's')
OH MY GOD THE FILE IS NAME 'S'
WHY THE FUCK IS THE FILE NAMED 'S'
no no no nonnonnnoonnoonnonno i swear im changing that. im doing it. 

okay i give up trying to understand this file
fuck software



....i will finish this tommorow. right now. Im going to sleep

**Review by LanaTomlin — APPROVED** [review]
go

**Pull request merged**
