### PR TITLE
RLCS Relay Board Respin Schematic

### PR DESCRIPTION
**Pull request by kfdliu**
Project Proposal: https://uwaterloo.atlassian.net/wiki/spaces/ROCKETRY/pages/43259789479/RLCS+Relay+Board+Respin

There are 3 identified sources of kickback voltages:
1. SPST relay (across CIN and COUT) - previous version already deals with kickback here via flyback diode (D1 in schematic)
2. DPDT relay (across CIN and COUT) - previous version also deals with kickback here via flyback diode (D2 in schematic)
3. Actuator (across P1/P2 and G1/G2) - solution with fewest components is adding two zener diodes (rated for V_z = 15V) in across P1 and G1. This should limit the kickback voltage across the actuator terminals to ~ 15-16V, reducing the likelihood of blowing the fuse connected to actuator power.

Unsure about the current rating required for the zener diodes (current rating on actuator?)
Also, is there a preference for SMD vs. through-hole diodes? Flyback diodes in existing design are through-hole.

- - -
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/rlcs/39)

### CODE REVIEW

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
A good start, some changes to make:

1. We don't need to explicitly track each new revision in a folder, that's what git does for us automagically! Instead, please replace the existing design in the repo.
2. The old kicad project for relay board v3 was all kinds of messed up, we should take this as an opportunity to clean it up. All the `rlcsv2_modular` stuff in the `schematics/` folder should go, and we should remove the `_v4` from the relay board folder and project names. Also all the different .pro files in the relay board schematic folder are out of place, there should only be a single root project. Also all those extra .sch files that are unused should be deleted, its a single page schematic so only need the one `rlcs_modular.kicad_sch`. On that note we should rename everything from `rlcs_modular` to `relay_board`.
3. I don't believe your protection diodes are correct. [This](https://assuredautomation.com/literature/V4_datasheet.pdf) is the datasheet for our actuators, it has a schematic in the bottom right of the last page. I've simplified it and drawn out the table of states, the values we want to protect with the diodes are the `-BIG` that occur when power to the motor is switched off by the limit switch. To do that I think we need a (regular, not zener) diode pointing from GND to G1 and G2, right? We did this successfully on all the copies of relay board currently inside RLCS, we should check how they are wired to make sure we have it right. (Note: I very well could have messed up writing this out, please check it)
image
4. The other half of this respin is that we want to flip around how the daisy chained connectors are wired so that we don't need to twist the connections between two adjacent boards. To that end you'll need to flip one of the 5-pin and 2-pin connectors, so pin 1 goes to pin 5, pin 2 to 4, etc.

**Comment by kfdliu** [comment]
Added the requested changes. One small issue with renaming files though. KiCAD seems to not like renaming the symbol library file (results in an error when trying to update symbols even after readding the new file as a symbol library).

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
Looking much cleaner, nice!

1. I think this is the correct set of diodes to add:
image
You should definitely either check yourself or get someone else to check how it's currently done on RLCS.
2. I think with renaming the library you might need to remove and re-add all the affected symbols to get them to update. Not certain though.

**Review by BluCodeGH — APPROVED** [review]
LGTM. I think we should drop the current sense resistors down to 0.01R since currently they can only measure about 2A.

Lets try to get another pair of eyes at least on it before going to layout.

**Comment by Rio6** [comment]
圖片
will the board always be connected to a board with I2C pull-ups when powered up?

圖片
This resistor does 't have a value

圖片
Does it really make sense to put the diodes here? I thought we're protecting the INA180s.

When there's a huge inductive load, switching it off would pull P1/P2 below GND and G1/G2 to some high voltage. INA180 won't handle the negative common mode voltage.
圖片

If we do this instead we can protect the INA180s from negative voltage (Vf should be <= 0.2V but probably fiiiiine with bigger one, anything is better than nothing). Also the diodes will need to handle the same magnitude of current as the load.
圖片

Or we can just put the current sensing behind the relay and let the relay eat the voltage (although some protection is still needed, just not as tight as 0.2V). With the setup we have right now only one of the output will be on at one time anyways.

I know there's no polarity but why is  current going into Cout and coming out from Cin :P
圖片

**Comment by BluCodeGH** [comment]
Rio, see the diagram I drew out. We can't short G1/G2 (pins 2 and 4 in the diagram) since they will sometimes have different voltages. I'm pretty sure that given the circuit I drew out the only inductive spikes are that -BIG on G1/G2, but if you're in person it would be very helpful for you to look at the underside of the relay boards in RLCS to verify the (successful) protection we installed there.

**Comment by Rio6** [comment]
> 

Ok I understand what your diagram means now XD. Although I can still think of scenarios where having only diodes on the G1/2 side would not protect the IC, I'll take a look at the relay board we have.

**Comment by kfdliu** [comment]
Addressed changes from above comments.

Current board has diodes from GND to P1 and P2 (D6/D7). Diodes from GND to G1 and G2 (D3/D4) are preferred, but the pads for the existing diodes will be kept in case (and marked as DNP) we need to switch back.

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
We need to flip the 5 pin and 2 pin screw terminals that connect to the daisy-chain boards around, since the CAN support board was already ordered it gets to define the correct orientation. See: https://waterloorocketry.slack.com/files/U019MS7MWPQ/F04JELWKC4C/20230110_223526.jpg

Otherwise LGTM

**Comment by eliaskountouris** [comment]
LGTM

**Comment by BluCodeGH** [comment]
Looks good except for one subtlety: There is no longer a good connection between the GNDs of the 2-pin screw terminals. Since this is the connection where we need to pass ~10A through we need to make sure both the 12V _and_ GND "traces" are very thick and straight.

**Review by JekkuChen — APPROVED** [review]
Nothing else to add beyond what was said. LGTM!

**Comment by rdakhil** [comment]
Looks good! Just a few comments on placement:

1. Current sense amplifiers and their shunt resistors should be routed with a bit more caution than other circuits. The INA180 datasheet (see Figure 9-7) has some layout and routing guidelines that you can follow. The more important part is the bit about using a "kelvin connection" to your shunt resistors, which reduces contact resistance that can cause errors in your current measurements
2. This board is kinda busy so it might not be possible, but it is recommended to put your 0.1uF bypass caps as close as possible to the IC power input and GND pins, for your INA180 current sense amplifiers and PIC18 caps C1, C2, and C3

**Comment by jasonskells** [comment]
Not much else to say as the previous feedback is pretty comprehensive. I did however notice that you're missing a 0.1uF decoupling cap on the PIC's VDD, I also don't think the 22uF cap is necessary, although it won't hurt to keep it on this board.

**Comment by jasonskells** [comment]
As for the layout, I have some feedback.

image

- The larger, high power traces should have priority over the smaller, logic signal traces. The main power trace has a poor current path. Ideally, you want to make this high-power traces as thick and as short as possible to decrease resistance. In yellow, I've drawn a more direct current path for that trace, and a new via placement in purple.
- Another critical issue I've noticed is the current return path. The screw terminal's GND pins do not have a clean and clear connection.
- The 5V trace should not be routed around the entire board as it cuts off the GND plane. You can drop a via near pin 14 on the PIC and continue the 5V trace to U7 on the top layer.
- Nitpick: I've noticed in many spots on the board, there are acute angles where the traces branch off (12V trace circled in green). These are potential acid traps which can eat away at the trace. This isn't really an issue with thick traces and modern manufacturing processes but for best practices I would recommend fixing them if you have the time. (when connecting 3 traces, it's best to try to make a "Y" shape with the traces if possible).

**Comment by kfdliu** [comment]
Implemented the changes recommended by Randy and Jason

**Review by BluCodeGH — APPROVED** [review]
Looks much better. Nitpicky routing comments to follow:

1. I think you can fit a trace in here to greatly simplify the 12V line, also you have an unnecessary via pair.
image
2. Your ground connections up here are really tenuous, I'd recommend adding some traces up to the pours above and pls don't daisy-chain through SMD pads (if a daisy-chained pad tears off then the board is way harder to salvage in the desert)
image
3. More daisy chaining, also look at how long and convoluted the paths from this capacitor the the PIC's power pins are. I'd probably place the cap just to the left of the pic so at least your +5V line is short.
image
4. You have a right angle on the trace between R13 and the pic.
5. More daisy chaining on R7, R9, Q1, PIC +5V pin

**Comment by kfdliu** [comment]
Hopefully its good now haha 🙏

**Pull request merged**
