### PR TITLE
Powerboard shield

### PR DESCRIPTION
**Pull request by Pangolinss**
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/rlcs/20)

### CODE REVIEW

**Comment by zx100x100** [comment]
Comments on things that need to get done for the schematics still:

- I noticed that the big connector only has 32 pins, compared to the 36 on the actual board. while it was likely intentional to ommit the 2 ground pins and 2 5V pins it would be good to have these in the schematic as we want to use a 36 pin header to fit the Arduino nicely.

- you can delete all the net labels for valve control as the valves are controlled Via i2c
(the power, select, and limitsw labels) 

- you already removed the 15V regulator. The J5 15V connector still needs to be removed

- remove header 1 that is attached to the 7 seg display and add the net labels that mach the labels in the Arduino connections sheet.

- it would be good to add a reset button on the shield for resetting the Arduino, this is just a button connected to the reset and ground that pulls the reset line low when pressed.  

- you need to add 2 i2c connectors for the i2c bus, these are the 5 pin jst connectors used on the i2c valve board, copy the pin out for the connector from that board.

- you can delete J7, please attach the net labels for the SD card pins to the appropriate Arduino pins on the connectors you added
image

**Comment by zx100x100** [comment]
Alright, looks like you are making good progress, A couple things:
1. A note on reference designators : U is the standard reference designator for microchips, J is normally used for connectors. A lot of your connectors currently use U as the designator, can you please go through and fix all of these.

2. It looks like you still haven't deleted J7, make sure you do that as this connector is unnecessary. That being said you do still need to connect the SD card to the Arduino, make sure you attach the net labels for the SD card to the appropriate pins on the Arduino (As defined in the tower pin defines code). 
image
you actually have one of the net labels for the SD card already, but the name doesn't match the rest of the schematic.
image

3. I'm not sure why you have these linear actuator power and select net labels, but please remove them. (if you are unsure about how something on this board is supposed to work please ask) Those labes are currently attached to the 2 5V pins on that connector, when you remove them please connect those pins to the +5V net (this will power the Arduino from the 5V regulator)
image

4. You have some weird naming for your arduino pins - I would make all these names what is physically written on the Arduino.
image

5. looks like you added the programming header from the I2C valve board, not the 2 copies of the I2C connectors. When you add these also please make sure you connect them to the I2C pins of the arduino, (you can look up which pins these are), you will also need to add pull up resistors, I think this article covers it well, but I would encourage you to do more learning as well: https://learn.sparkfun.com/tutorials/i2c/i2c-at-the-hardware-level
image
image

**Comment by zx100x100** [comment]
Alright, comments on latest commit:

1. This connector still has a U reference designator, please correct it it J like all the others. 
Also while I noticed you fixed the pin-out on this connector, you now have the reset button connected to the wrong pin. Also, the 3.3V pin is currently labled as 1.3V, please fix this.
image

2. 
You seem to have created some sort of strange 10 pin connector with repeated pins, this is supposed to be 2 five pin connectors, which happen to be beside each other. I would use the exact part from the Relay boards.
image

3. You did a good job adding the net labels for the 7-segment display to the arduino connectors, but you didn't add them to the 7-segment display
image

4. There is a discrepancy in the 12V net label name, it needs to be consistent for there to be a connection. I would probably replace the 12P power labels with the 12V ones
image

let me know if you have any questions, and if you want to, we could hop on a call to go through this.

**Comment by jacobdeery** [comment]
How many of these files should actually be tracked in Git? I'm not familiar with how KiCad projects are structured, but there are an awful lot of `-bak` and and `rescue-backup` files floating around in here that don't really look like they should be tracked. @zx100x100 can you comment?

**Comment by QuantumManiac** [comment]
Yeah, that's a good point actually. I didn't notice the `rescue-backup` but the folder should probably have been deleted once the files were recovered. 

I think it might be worth adding a `.gitignore` to get rid of all the unnecessary files entirely. If I remember correctly, Github has a template for it for KiCAD so that might be worth looking into.

**Comment by AidanHa** [comment]
My comments:

You got a weird floating "arduino" silk screen floating 
image

It feels like the SD card will be hard to reach without taking the shield off from the arduino... Here's a picture of the current board 
image

If you have time (and effort lol), then would it be possible to rearrange the components to have easier access to the sd card? Otherwise it's fine as it is.

Good work! I think you can start with the routing/tracing.

**Review by zx100x100 — CHANGES_REQUESTED** [review]
Overall looks like good progress, I like how you have arranged a number of things. Still a few things need fixing though.

1. I like the SD card location, but we will need to be careful to get headers tall enough to make sure the SD card clears the USB connector on the Arduino. that being said it sticks out right now (note the silkscreen goes of the board) we should fix this. don't worry we should still be able to get the SD card out, but we don't want the holder sticking over the edge.

2. SW1, the reset button is currently a switch, this would technically work but it would be annoying as you would need to flick it one way and then the other. Setting this to a normal tactile switch such as the SW_PUSH_6mm footprint

3. JP1 is still a 90 degree harder, see previous comment but TLDR is make it a vertical header instead

4. J4, the main power connector needs to accept some beefy 12 gauge wire in the side, you won't be able to get that in how it is right now. It should really be right against the side of the board. so it's easy to install those wires.

5. you have some VERY beefy traces, some of which really don't need to be. here is a calculator for trace width based on current, (keep in mind the team minimum is 8 mil).  I'd encourage you to try and figure out the max current on each line yourself, feel free to message me in electrical if you need a hand.

Also generally we will route power last as we will have a power and ground plane which will do most of the routing for us.

**Comment by AidanHa** [comment]
Layout looks fine to me, you might want to update the silk screen with the proper date (and maybe while youre at it, add the rocketry logo
image

Sorry for the delayed review. Feel free to start your routing!

**Comment by zx100x100** [comment]
Looking pretty good, I still have a few comments:

1. the SD CARD silkscreen still sticks off the board, it needs to get pushed back just a little farther I think.

2. the bypass capacitors for the voltage regulators (C1 and C2 for T1, C3 and C4 for T2) should be right beside the voltage regulators.
This video is pretty long but it gives a visual for why this is the case: https://youtu.be/1xicZF9glH0

3. when you move on to your routing feel free to move a couple parts around. for example I think you will find your routing is much cleaner if you put the fuse right beside the input terminals instead of routing power all the way across the board unessisairly.

4. you could probably stand to space out your resistors a little more, a gap equal to the width of the resistor is usually about right. This is so that assembly or repairs are easier.

**Comment by AidanHa** [comment]
Hey! Sorry for the super late review. Here are some thoughts:

Rather than connecting each ground, 3v3 and/or 5v5 pad, I wouild recommend using a copper pour. Usually I do a copper pour for all my ground pins, but I know some boards that others have designed have used copper pours for 3v3 or 5v. Makes routing alot cleaner.

Feels like your trace sizes are all over the place. For example, the 12V line has a super small trace at :
image

Another example the 5V trace looks huge: 
image


Not too sure if this was done on purpose according to the datasheet of some parts (can someone confirm), but from looking at the board, alot of traces could be smaller/resized. you can use the `rlcs/schematics/relay_board_v2_schematics` as kind of a "guide" as to figuring out which traces should be what size.


The sd card reader (j1) doesnt have a silkscreen. Could you add one? it makes soldering easier
image

Couple of places where silk screen overlap: 
image

That's all for now. Good start for the moment, but could use some cleanup! Good work!

**Comment by ZTeper** [comment]
Comments:

- Add Rocketry logo to PCB, update title and date silkscreen
- Add current ratings for the fuse and regulators
- Check whether R4 is physically blocking the SD card
- Vias should never touch solder masks (e.g. R17)
- 7-segment display appears to lack a ground connection. Check whether this is correct.
- Consider adding a current-limiting resistor to the push-button switch
- Keep traces away from "courtyards/keepout areas" for solder masks (e.g. C3)
- Why are Q1 and Q2 duplicated on the PCB, but not on the schematic? Please explain.
- Avoid daisy-chaining traces through drill-holes (e.g. +12V connection on the fuse)

Keep up the good work!

**Review by LanaTomlin — COMMENTED** [review]
Hello! 
This is extremely late, however, it doesn't look like anything has changed, so here are my two cents, I suppose.
1. What is D1? I see the label, but I don't see any silkscreens that look like a diode. Maybe I'm missing something.
2. I believe this was mentioned already, but labels for R9 and R14 are overlapping. 
3. There are two R17s, and two R18s. 
4. I don't know if this causes issues or not, but a bunch of the +5V vias overlap with resistor pads (Specifically R18 and R17). There's also overlap with the J14 connector.
5. Is there a reason the VIAs are different sizes?
6. The label for TP4 is hidden behind a trace. 
7. Labels for JP1 and TP3 are overlapping
8. There are a couple of what look like silkscreens on the B.Fab layer, is there a reason for that?
9.  Labels for R16 and R1 are overlapping
10. You've got traces that are going to be hidden under J11, might want to make those visible. 
11. The REFDES labels for F1 and AFF! are grey and I don't know what to make of it. 
12. AFF1 is going to hide a lot of traces - but I don't know how fixable that is. 
13. R2, R1, and R16 have traces that go straight between them - I would recommend pulling them out so they look like little mountains so they're visible on the board. 

Hope I was able to be helpful!

**Comment by AidanHa** [comment]
My review:

Quick run of drc says there are errors Should be quick to address:
image

90 degree con between R2 pad 2 and R1 pad 1
image

Would it be possible to change the layout to have the sd card on the top of the board rather than on the bottom, I feel like the sd card wont be accessible if facing the bottom. There's a chance that the sd card but cause the shield to not fit properly on the arduino mega 2560. If you can visualize it, the sd card at the facing down towards the arduino makes a "bump". Feel free to dm me if my explanation wasn't clear. This point is also open to conversation. (Sorry, this might be tedious).

Some traces fel a tad bit small (eg r18 annd r17 pad 2), especially since some of them are carrying 5 volts. Could you increase the width of the traces to 0.4mm. This might not be enough but we'll see how it looks for now

traces can be cleaned up here
image

**Comment by MattiGen** [comment]
Closed to keep task organized. New PR will be created for part layout/routing.

**Pull request closed without merging**
