### PR TITLE
Can support

### PR DESCRIPTION
**Pull request by DomenicHampson**
Hello, please take a look at the schematic for the hardwired CAN support board and let me know if there is anything I should add or change. Thank you!

- - -
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/rlcs/37)

### CODE REVIEW

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
1. You need a second screw terminal like J4 for the 12V to pass through, just like how we have 2 of the 5-pin connectors.
2. Last I heard @jasonskells actually requested 24V for the umbilical rather than 12. We can pull that from ground power distribution by just wiring it from the connector into this board, but it means adding in an extra screw terminal for that wire.
3. Probably good to add some text comments explaining stuff, eg that we pass through the +12V on the 5 pin connector without using it.
4. One of the biggest problems with relay board is that on the 5 pin connectors, pin 1 is connected to pin 1. This means that when wiring two adjacent boards together we need to put a twist in the wire to "undo" that mapping. We should update this board to flip one of those connectors, ie have 1 on one connector connect to pin 5 on the other, pin 2 to 4, etc.
5. We're getting into nitpick territory but your wiring could be a bit tidier. I've written up some general stuff [here](https://uwaterloo.atlassian.net/wiki/spaces/ROCKETRY/pages/42646503921/Schematics), specific points below:
6. Given that everything has netlabels (well done) I think it would be cleaner to put all the testpoints together in the corner just connected to their specific netlabel. That makes it easier to map between test points and nets from looking at the schematic, and it makes the rest of the schematic easier to read too.
7. Please make sure your grid is set to 1.27 mm (0.05 in). Most footprints are designed to work nicely with a 0.05 in grid, and a lot of stuff here is slightly off that grid which just makes things line up a bit worse.

**Comment by Rio6** [comment]
圖片

Is it OK to use +5V for Vio here? Other CAN boards I see uses 3v3.

**Comment by BluCodeGH** [comment]
You'll see a mix of 5V and 3V3 Vio, it has to match the voltage of the PIC for them to talk.

**Review by QuantumManiac — COMMENTED** [review]
LGTM schematic-wise. Once Jack gives his approval you should be good to proceed to PCB layout

**Comment by Rio6** [comment]
圖片

What's this trace for?

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
Layout looks pretty good, although its always nice to have test points all together and along one board edge for easy access. TP2 and 3 specifically will be hard to get at between those connectors. The routing needs some work:

1. There are a lot of 90 degree intersections between traces. This is generally regarded as bad practice, it won't break your PCB when stuff is simple like this but it's a good habit to get into routing things with exclusively 45 / 135 degree angles.
2. Maybe you didn't save before committing but your bottom ground pour wasn't filled. In order to "fill in" the ground pours you need to press "B" and let it think. You should do this frequently (just as often as you save if not more), as you route traces the ground plane needs to be updated to go around them.
3. You should also have a top ground pour. Then you don't need any of your manual GND routing, its all just connected to the pour automatically. Having a top pour also further prevents noise.
4. You should center the crystal oscillator with the OSC pins such that the traces are equal length. Likewise the traces to the oscillator capacitors should be symmetric / equal length. Lastly it's good practice to put a bunch of GND vias around the oscillator / its capacitors and not route an traces nearby.
5. If you look at J5 and J6 and imagine having a bunch of copies of this board in a row you'll see that you'd need to cross the 12V and GND wires over between the boards. We want to avoid this in future RLCS boards, so I suggest you swap the pinout of J6 in the schematic (ie have ground always closer to the 5 pin connector).
6. Those J5 and J6 connectors need to pass through enough current to actuate our valves, right now if you put this board in RLCS those tiny traces would catch on fire. Anything that's high current should have a bigger traces. Specifically I'd make the 12V and GND lines between the two connectors as fat as you can fit, and also beef up the 24V connection to the relay and from the relay to the rocket. Use an online trace width calculator (size for maybe 3A) to find the width.
7. You're missing silkscreen labels. All connector pins should be labeled except the programming connector which only needs MCLR labeled. You should also label the test points and put your name, the date, the board name, and the team logo somewhere.
8. Gettting nitpicky now but I think rounded corners make our boards look professional. You also have one trace running right along the left edge, just for peace of mind I'd bring it in a bit.

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
Tracing looking much better now, nice work! A number of smaller details to fix:

1. I would recommend routing the 12V line like this, it needs to handle ~10A:
image
2. Note that the only other thing using 12V is the relay coil which probably only draws on the order of 50 mA, so the standard 8 mil traces are fine for that.
3. Likewise for 24V the only traces that need to be thicc are from the screw terminal to the relay input and from the relay output to the output screw terminal - everything else (ie the line to the test point) should be the standard 8 mil.
4. Please don't use the `rocketry_logo_small` footprint, it's all squished! You can use the no-text version if you're space constrained.
5. I'd remove the underscores in your CAN_H and CAN_L test point names since they are a bit too wide rn.
6. You should always run the design rule check tool before finalizing. It's pointing out to me that your board outline isn't quite perfectly connected in the lower left corner and that a couple GNDs aren't connected. Even though you have a ground pour, if things are routed too tightly they can cut off some GNDs and you're left with things being disconnected. In that case it's fine to route those ones manually.
7. Sorry for not catching this during layout but decoupling capacitors (ones between a voltage rail and GND to reduce noise, here C3 and C4) should be placed as close as possible to the power input to the component they are for. So we can see on the schematic that C3 should be placed next to the PIC, and C4 should be moved closer to the 5V pin on U3.
8. If you look around each footprint there is a bounding box called the courtyard, this is roughly how much physical space that component takes up. Generally the silkscreen will also reflect the bounds of the components. Right now most of your pin labels on the connectors will end up underneath those connectors so they won't be readable! To find issues like this I recommend using the 3d viewer (alt+3).
9. Please remove the `REF**` silkscreens on the mounting holes.

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
Almost there! A few tweaks and we should be good to go:

1.The gnd line of the two-pin 12V screw terminals will also have that same ~10A flowing back through it. Using the ground plane to route that is totally fine, but you need to make sure the plane isn't all cut up if you do so. Right now there are two traces on the backside that prevent a nice clear path, if you could just shift them both up by about the same height as that thicc 12v trace things would be much better.
2. Your 5-pin connections aren't routed too efficiently, which mostly matters for its 12v line which will see maybe 100-200ma. You'll see SCL does a big loop around the oscillator, if you move it to loop above the oscillator that should free up a lot of space for much more direct 5v and 12v traces. You could also make those 5v and 12v passthrough traces a bit bigger just for good measure.
3. Right now the silkscreen labels for the 5 pin connectors are hard to read since it looks like one long word, I'd rotate the labels 90 degrees to fix this. Also good to add the 12v label on the 5 pin connector even though you don't use it.
4. The decoupling capacitors are pretty close to the ICs, so it will be a bit tricky to solder rn. I'd back them off by one capacitor width.
5. Also if you think about how you'd typically be plugging wires into a board like this, you'll have the open side of the connector facing you so you can see where you're plugging the wire in. That means that your screw terminal labels would be upside down, so I'd flip them all around.

**Review by BluCodeGH — APPROVED** [review]
LGTM, but let's get some more eyes on this before ordering.

**Comment by eliaskountouris** [comment]
lgtm

**Comment by BluCodeGH** [comment]
Correct the pullups are on the master (powerboard shield)

**Review by QuantumManiac — APPROVED** [review]
LGTM! The schematic PDF is currently blank. Would be good to re-plot it.

**Comment by DomenicHampson** [comment]
Will update the pdf tonight. Thanks everyone for looking at it. Is the board good to be ordered?

**Comment by BluCodeGH** [comment]
Yep, we should be good to order. I think we can also squeeze #38 into this order if we delay by a few days which is worthwhile, so we'll leave this PR open until we order.

**Pull request merged**
