### PR TITLE
RLCS master Code Cleanup

### PR DESCRIPTION
**Pull request by AidanHa**
This PR serves 2 major purposes:
- Organize, document and merge code found in the cleint_v3 branch.
- Add additional cleanup/infrastructure code including code to tidy up master code.

One of the major changes in the PR is the renaming of valves in the code base. For the sake of modularity, rather than giving each specific valve a label (ie: remote fill, remote vent), we will give them a generic number (1,2,3,4). This way, the valves are all interchangeable (with no label), and we can and remove labels depending on future use cases. In the change list below, "valve name changes" refers to the change above.

Below is a change list which defines the parts of RLCS code that are to be changed/updated. Note that most header files were not mentioned in the change list, but are included in the PR. The reasoning for this is that the header file changes reflect off the same changes as their appropriate .c or .cpp files.

Client LCD.cpp
- Modify code to change the information displayed on the Client LCD. 
- This includes realigning information such as current lines and valve lines, adding an additional valve line for the liquid engine, adding a battery line and removing the old mass and disconnect lines on the LCD.
- Rename valve variables for the sake of the valve name changes.
- Remove old code that wasn't used in the new display code.

client arduino_ide.ino
- Modify code to only read button states in the system is armed.
- Add changes to turn on the switch LEDS of ONLY all active switches if armed.
- Add changes to read which buttons/switches are in use.
- Add change to read battery voltage input.

Client globals.c
- Rename valve variables for the sake of the valve name changes.
- Add pinout for reading battery voltage.
- Add pinout for an additional blue LED.
- Add support for 8 additional switches (with the new client side box).

Client pin_defines.h
- Note: did not move/modify pinout of current arduino.
- Simply added pin definitions for the new switches and fore the new LED.

Client shared_types.cpp
- Rename valve variables for the sake of the valve name changes.

For the entirety of tower side RLCS, remote fill and vent valves will be renamed to valve_1 and valve_2 respectively. the linac valve will be renamed to valve_3 and an additional valve_4 was added (I think to rename the relay board responsible for ignition but I'm not too sure).

Tower pin_defines.h
- Rename valve variables for the sake of the valve name changes.

Tower injector.c
- Move and commented out liquid injector code, which is to be used in a future date.
- This code will be integrated in the upcoming "loadout" pr.

Tower linac.c
- Comment out all linac code. the linac relay board slot is to be used as a 3rd generic valve board, so the code is meaningless for the moment.

Tower nodeio.ioio.cpp
- Add type cast to injector valve state for the sake of robustness.

Tower shared_types.cpp
- Rename valve variables for the sake of the valve name changes.

Tower arduino_ide.ino
- Comment out code for liquid injector.

Tower daq.c, globals.c and
- Rename valve variables for the sake of the valve name changes.
- There might seem to be a lot of changes, but all of the changes involve renaming variables.
- Add hard coded safe state for the valves (valve 1 open, valve 2 open, valve 3 close, valve 4 close). This can be modified in the future.

Tower pin_defines.h
- Add A0 as a placeholder for sensors that are not in use.
- Change linac (now valve 3) power and select from pin 22 and 23 to 9 and 8.
- Add valve 4 power and select pins to pin 36 and 37.
- Change secondary ignition pin current (PIN_CURRENT_IGNITION_SEC) to A8
- Change PIN_BATTERY_MAIN and  PIN_BATTERY_ACTUATORS from A1 and A0 to A3 and A2
- Change pinouts of primary  and secondary ignition.

---
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/rlcs/27)

### CODE REVIEW

**Review by jacobdeery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/rlcs/27)* status: 0 of 21 files reviewed, 9 unresolved discussions (waiting on @AidanHa, @BluCodeGH, @JaredWatson, and @zx100x100)

___
*[src/client_arduino_ide/client_globals.c, line 35 at r1](https://reviewable.io/reviews/waterloo-rocketry/rlcs/27#-MTcIUSB3ljkMB9-DJ6d:-MTcIUSB3ljkMB9-DJ6e:b-wcnylg) ([raw file](https://github.com/waterloo-rocketry/rlcs/blob/366d4ac3a7416f742d8258d0f21fadedc78d1280/src/client_arduino_ide/client_globals.c#L35)):*
> ```
> button_t injector;
> ```
any reason to not rename this one as well?
___
*[src/client_arduino_ide/LCD.cpp, line 116 at r1](https://reviewable.io/reviews/waterloo-rocketry/rlcs/27#-MTcIqOcEFCnpGIzbbg8:-MTcIqOcEFCnpGIzbbg9:b9q78jd) ([raw file](https://github.com/waterloo-rocketry/rlcs/blob/366d4ac3a7416f742d8258d0f21fadedc78d1280/src/client_arduino_ide/LCD.cpp#L116)):*
> ```
> bellow
> ```
below
___
*[src/tower_arduino_ide/injector.h, line 7 at r1](https://reviewable.io/reviews/waterloo-rocketry/rlcs/27#-MTcJ2hG9WHaUl8Ssh58:-MTcJ2hG9WHaUl8Ssh59:b-sidcaj) ([raw file](https://github.com/waterloo-rocketry/rlcs/blob/366d4ac3a7416f742d8258d0f21fadedc78d1280/src/tower_arduino_ide/injector.h#L7)):*
> ```objc
> extern "C" {
> #endif
> // don't want to delete, but we aren't using liquid any time soon
> ```

Let's just delete all of this commented code. All of this is likely to change significantly by the time we get to liquid, and if we really need it later we can restore it from the git history.
___
*[src/tower_arduino_ide/linac.c, line 33 at r1](https://reviewable.io/reviews/waterloo-rocketry/rlcs/27#-MTcJVxZ0hCYOaNdP01s:-MTcJVxZ0hCYOaNdP01t:b-pzzo2y) ([raw file](https://github.com/waterloo-rocketry/rlcs/blob/366d4ac3a7416f742d8258d0f21fadedc78d1280/src/tower_arduino_ide/linac.c#L33)):*
> ```C
> 
> //public functions
> void linac_init()
> ```

What's going on here? Why is all of this commented?
___
*[src/tower_arduino_ide/tower_arduino_ide.ino, line 73 at r1](https://reviewable.io/reviews/waterloo-rocketry/rlcs/27#-MTcJaxyAS6uEn6Vv5fF:-MTcJaxyAS6uEn6Vv5fG:b-rtagwg) ([raw file](https://github.com/waterloo-rocketry/rlcs/blob/366d4ac3a7416f742d8258d0f21fadedc78d1280/src/tower_arduino_ide/tower_arduino_ide.ino#L73)):*
> ```cpp
>     //deal with the liquid injector
>     //fuel_injector_refresh();
>     //ox_injector_refresh();
> ```

delete
___
*[src/tower_arduino_ide/tower_arduino_ide.ino, line 82 at r1](https://reviewable.io/reviews/waterloo-rocketry/rlcs/27#-MTcJcFZ3gMW5KJ2dK1L:-MTcJcFZ3gMW5KJ2dK1M:b-b72gi7) ([raw file](https://github.com/waterloo-rocketry/rlcs/blob/366d4ac3a7416f742d8258d0f21fadedc78d1280/src/tower_arduino_ide/tower_arduino_ide.ino#L82)):*
> ```cpp
>     char to_put_on_sevenseg;
>     if( convert_state_to_radio(get_current_state(), &to_put_on_sevenseg) ) {
>         // DEPRECATED: setNewNum_SevSeg( (uint8_t) fromBase64(to_put_on_sevenseg) );
> ```

why not just remove the old line?
___
*[src/tower_arduino_ide/tower_globals.c, line 95 at r1](https://reviewable.io/reviews/waterloo-rocketry/rlcs/27#-MTcJit3DpmhXDFoIQ5i:-MTcJit3DpmhXDFoIQ5j:b-9i3xqa) ([raw file](https://github.com/waterloo-rocketry/rlcs/blob/366d4ac3a7416f742d8258d0f21fadedc78d1280/src/tower_arduino_ide/tower_globals.c#L95)):*
> ```C
>         }
>     }
> /*
> ```

Why commented?
___
*[src/tower_arduino_ide/tower_globals.c, line 198 at r1](https://reviewable.io/reviews/waterloo-rocketry/rlcs/27#-MTcJqjB2elIEL8MWIfE:-MTcJqjB2elIEL8MWIfF:b-bxbhvx) ([raw file](https://github.com/waterloo-rocketry/rlcs/blob/366d4ac3a7416f742d8258d0f21fadedc78d1280/src/tower_arduino_ide/tower_globals.c#L198)):*
> ```C
>     //TODO, figure out how the run tank valve is going to work
>     //likely involve a serial link to another arduino
>     //I don't think this should be here, we have RocketCAN - Zach 2020-02-20
> ```

If it shouldn't be here, we should delete it
___
*[src/tower_arduino_ide/tower_globals.h.gch, line 0 at r1](https://reviewable.io/reviews/waterloo-rocketry/rlcs/27#-MTcJxenC3s1u8cM_ACS:-MTcJxenC3s1u8cM_ACT:b-1k157r) ([raw file](https://github.com/waterloo-rocketry/rlcs/blob/366d4ac3a7416f742d8258d0f21fadedc78d1280/src/tower_arduino_ide/tower_globals.h.gch#L0)):*
I'm not sure if this belongs in git (I'm inclined to say no)

**Comment by AidanHa** [comment]
> What's going on here? Why is all of this commented?

Seems like for the recent SF, we used a third valve in place of the linear actuator. It's commented out for now to get the 3 valve system working I assume. @zx100x100 are we good to uncomment the linac code?

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
> Reviewed 21 of 21 files at r1.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/rlcs/27)* status: all files reviewed, 12 unresolved discussions (waiting on @AidanHa, @JaredWatson, and @zx100x100)

___
*[src/client_arduino_ide/client_globals.c, line 141 at r1](https://reviewable.io/reviews/waterloo-rocketry/rlcs/27#-MTcMTgEAyFZgAzyycAJ:-MTcMTgEAyFZgAzyycAK:b-4d85hg) ([raw file](https://github.com/waterloo-rocketry/rlcs/blob/366d4ac3a7416f742d8258d0f21fadedc78d1280/src/client_arduino_ide/client_globals.c#L141)):*
> ```C
> }
> 
> void init_buttons()
> ```

This seems to initialize more than just buttons nowadays.
___
*[src/client_arduino_ide/LCD.cpp, line 68 at r1](https://reviewable.io/reviews/waterloo-rocketry/rlcs/27#-MTcOb1z7wGfBcaHwWCC:-MTcOb1z7wGfBcaHwWCD:b-7iwy8y) ([raw file](https://github.com/waterloo-rocketry/rlcs/blob/366d4ac3a7416f742d8258d0f21fadedc78d1280/src/client_arduino_ide/LCD.cpp#L68)):*
> ```cpp
> static void display_battery_line(uint16_t tower_actuator_batt, uint16_t tower_main_batt, uint16_t client_batt);
> 
> // not using thease
> ```

these
___
*[src/client_arduino_ide/tower_pin_defines.h, line 31 at r1](https://reviewable.io/reviews/waterloo-rocketry/rlcs/27#-MTcTvnW2G_WBlbtbglR:-MTcTqWp5LN6apqTm__T:b-pf66j4) ([raw file](https://github.com/waterloo-rocketry/rlcs/blob/366d4ac3a7416f742d8258d0f21fadedc78d1280/src/client_arduino_ide/tower_pin_defines.h#L31)):*
> ```
> #define PIN_LIMITSW_REMOTEFILL_OPN 34
> #define PIN_LIMITSW_REMOTEFILL_CLS 35
> ```
Shouldn't these be renamed as well?

**Review by AidanHa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/rlcs/27)* status: 12 of 20 files reviewed, 12 unresolved discussions (waiting on @AidanHa, @BluCodeGH, @jacobdeery, @JaredWatson, and @zx100x100)

___
*[src/client_arduino_ide/client_globals.c, line 35 at r1](https://reviewable.io/reviews/waterloo-rocketry/rlcs/27#-MTcIUSB3ljkMB9-DJ6d:-MU4yPIv7xmP9YEnwORd:bgsp9dx) ([raw file](https://github.com/waterloo-rocketry/rlcs/blob/366d4ac3a7416f742d8258d0f21fadedc78d1280/src/client_arduino_ide/client_globals.c#L35)):*
> any reason to not rename this one as well?
Zach probably wanted to separate the injector from the rest of the valves. For the sake of clarity, it should feel like it's separated, but the injector uses the same relay board as the rest of the valves, so it wouldn't hurt to rename. @zx100x100 thoughts?
___
*[src/client_arduino_ide/client_globals.c, line 141 at r1](https://reviewable.io/reviews/waterloo-rocketry/rlcs/27#-MTcMTgEAyFZgAzyycAJ:-MU4zBhw-90A6gPNPQzP:bhyimtj) ([raw file](https://github.com/waterloo-rocketry/rlcs/blob/366d4ac3a7416f742d8258d0f21fadedc78d1280/src/client_arduino_ide/client_globals.c#L141)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

This seems to initialize more than just buttons nowadays.
</blockquote></details>

I still feel like this is the correct name, as all we are doing is "turning on the buttons" (button input, LED, etc)
___
*[src/client_arduino_ide/tower_pin_defines.h, line 31 at r1](https://reviewable.io/reviews/waterloo-rocketry/rlcs/27#-MTcTvnW2G_WBlbtbglR:-MU5-NDn6OeRa8LOpatC:b-7wxu0) ([raw file](https://github.com/waterloo-rocketry/rlcs/blob/366d4ac3a7416f742d8258d0f21fadedc78d1280/src/client_arduino_ide/tower_pin_defines.h#L31)):*
> Shouldn't these be renamed as well?

I found out that the only file on the client side that uses this file is servseg.c. Aaron probably copy pasted this file in client and in tower bc the code should be same for both sevsegs. I concluded that this file can be safely removed from the client repo.

Tower repo didn't have an equivalent client_pin_defines.h, so no additional work needs to be done.
___
*[src/tower_arduino_ide/injector.h, line 7 at r1](https://reviewable.io/reviews/waterloo-rocketry/rlcs/27#-MTcJ2hG9WHaUl8Ssh58:-MU52EN752AWWP4Fqrb7:brxp9sq) ([raw file](https://github.com/waterloo-rocketry/rlcs/blob/366d4ac3a7416f742d8258d0f21fadedc78d1280/src/tower_arduino_ide/injector.h#L7)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

Let's just delete all of this commented code. All of this is likely to change significantly by the time we get to liquid, and if we really need it later we can restore it from the git history.
</blockquote></details>

Sounds good.
___
*[src/tower_arduino_ide/linac.c, line 33 at r1](https://reviewable.io/reviews/waterloo-rocketry/rlcs/27#-MTcJVxZ0hCYOaNdP01s:-MU52jPG81iccvlq7W43:bh72y8s) ([raw file](https://github.com/waterloo-rocketry/rlcs/blob/366d4ac3a7416f742d8258d0f21fadedc78d1280/src/tower_arduino_ide/linac.c#L33)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

What's going on here? Why is all of this commented?
</blockquote></details>

Looks like the linear actuator wasn't used last test, so everything was commented out. Uncommenting.
___
*[src/tower_arduino_ide/tower_globals.c, line 95 at r1](https://reviewable.io/reviews/waterloo-rocketry/rlcs/27#-MTcJit3DpmhXDFoIQ5i:-MU54AF-2eSF0j_CV5ai:bsty1wy) ([raw file](https://github.com/waterloo-rocketry/rlcs/blob/366d4ac3a7416f742d8258d0f21fadedc78d1280/src/tower_arduino_ide/tower_globals.c#L95)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

Why commented?
</blockquote></details>

Maybe to configure a past test? Uncommenting.
___
*[src/tower_arduino_ide/tower_globals.c, line 198 at r1](https://reviewable.io/reviews/waterloo-rocketry/rlcs/27#-MTcJqjB2elIEL8MWIfE:-MU54N-K5vrjwocifnpw:bs3362y) ([raw file](https://github.com/waterloo-rocketry/rlcs/blob/366d4ac3a7416f742d8258d0f21fadedc78d1280/src/tower_arduino_ide/tower_globals.c#L198)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

If it shouldn't be here, we should delete it
</blockquote></details>

I think it should be here, the linear actuator is technically an "output", so initing linac in this function sounds correct.

**Review by BluCodeGH — DISMISSED** [review]
> Reviewed 10 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/rlcs/27)* status: all files reviewed, 9 unresolved discussions (waiting on @AidanHa, @jacobdeery, @JaredWatson, and @zx100x100)

**Review by BluCodeGH — COMMENTED** [review]
Took another look at this, currently it looks like both linac.c and tower_globals.c are controlling valve 3 which I think shouldn't be happening. @zx100x100 can you confirm?

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/rlcs/27#-:-MVKhU7x53zMmflIJYpG:bdnnh6x)* status: all files reviewed, 9 unresolved discussions (waiting on @AidanHa, @jacobdeery, @JaredWatson, and @zx100x100)

**Review by zx100x100 — COMMENTED** [review]
Linac.c is used for the flight system when valve 3 is disconnect. otherwise it should be somehow disabled / swaped to being a normal valve

Overall nothing stands out to me but RLCS is a very temperamental code base and I'm not a big fan of merging this until it has been tested on hardware as the chances of subtly breaking something are very high.

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/rlcs/27#-:-MVL860J19NwC2QqkblH:b7wbrvm)* status: all files reviewed, 9 unresolved discussions (waiting on @AidanHa, @jacobdeery, and @JaredWatson)

___
*[src/client_arduino_ide/client_globals.c, line 35 at r1](https://reviewable.io/reviews/waterloo-rocketry/rlcs/27#-MTcIUSB3ljkMB9-DJ6d:-MVL4fIf2w0Q_6Jk86P4:b-z69h3c) ([raw file](https://github.com/waterloo-rocketry/rlcs/blob/366d4ac3a7416f742d8258d0f21fadedc78d1280/src/client_arduino_ide/client_globals.c#L35)):*
<details><summary><i>Previously, AidanHa (Aidan Ha) wrote…</i></summary><blockquote>

> any reason to not rename this one as well?
Zach probably wanted to separate the injector from the rest of the valves. For the sake of clarity, it should feel like it's separated, but the injector uses the same relay board as the rest of the valves, so it wouldn't hurt to rename. @zx100x100 thoughts?

</blockquote></details>

Injector is still named as such on client V3 where as all other valves are designed to be renameable. it is also the most common valve across tests IMO, there is almost always a valve that "does the thing". that being said, this is slightly arbitrary, so I probably won't kick and scream if you really want to change it.
___
*[src/tower_arduino_ide/tower_globals.c, line 198 at r1](https://reviewable.io/reviews/waterloo-rocketry/rlcs/27#-MTcJqjB2elIEL8MWIfE:-MVL7jZP9Hv-FGpnncad:b-q3n122) ([raw file](https://github.com/waterloo-rocketry/rlcs/blob/366d4ac3a7416f742d8258d0f21fadedc78d1280/src/tower_arduino_ide/tower_globals.c#L198)):*
<details><summary><i>Previously, AidanHa (Aidan Ha) wrote…</i></summary><blockquote>

I think it should be here, the linear actuator is technically an "output", so initing linac in this function sounds correct.
</blockquote></details>

I believe this is me talking about run tank valve (AKA vent valve), no reason to keep this todo

**Comment by AidanHa** [comment]
> Overall nothing stands out to me but RLCS is a very temperamental code base and I'm not a big fan of merging this until it has been tested on hardware as the chances of subtly breaking something are very high.

I thought master didn't work in the first place and these changes were to help to get it to work for the last SF? If that's the case then we should just merge it nevertheless.

**Comment by BluCodeGH** [comment]
I've tested this branch on hardware with no issues, the 3 normal valves work (including feedback) and I heard relay clicks for injector and ignition. I didn't do anything with `linac.c`, from what I could see the init/refresh functions are called but it is never actually called to actuate (even in anything commented out, which is a bit weird).

**Review by jacobdeery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/rlcs/27)* status: 21 of 23 files reviewed, 6 unresolved discussions (waiting on @AidanHa, @BluCodeGH, @Chrisc110, @dwkletke, @jacobdeery, @JaredWatson, @QuantumManiac, @wendi-yu, @ZTeper, and @zx100x100)

___
*[src/client_arduino_ide/client_globals.c, line 23 at r3](https://reviewable.io/reviews/waterloo-rocketry/rlcs/27#-MegcUSA-Qdk8jHcO2MO:-MegcUSA-Qdk8jHcO2MP:bmibnx4) ([raw file](https://github.com/waterloo-rocketry/rlcs/blob/029c859e6b7193078c29e50c4111d41cf9060d00/src/client_arduino_ide/client_globals.c#L23)):*
> ```
>     //.linac_lsw_extend = 0,
>     //.linac_lsw_retract = 0
> ```
remove
___
*[src/client_arduino_ide/client_globals.c, line 74 at r3](https://reviewable.io/reviews/waterloo-rocketry/rlcs/27#-MegdorJ0LkQZqdQojOd:-MegdorJ0LkQZqdQojOe:b-fij4ps) ([raw file](https://github.com/waterloo-rocketry/rlcs/blob/029c859e6b7193078c29e50c4111d41cf9060d00/src/client_arduino_ide/client_globals.c#L74)):*
> ```
> valve_1 ? 1 : 0;
> ```
why ternary?
___
*[src/client_arduino_ide/LCD.cpp, line 97 at r3](https://reviewable.io/reviews/waterloo-rocketry/rlcs/27#-MegeUdq5KghzqIFsiAC:-MegeUdq5KghzqIFsiAD:b-8ln3mc) ([raw file](https://github.com/waterloo-rocketry/rlcs/blob/029c859e6b7193078c29e50c4111d41cf9060d00/src/client_arduino_ide/LCD.cpp#L97)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>     if (millis() - time_last_line_switch > 2000) {
>         display_first_line = !display_first_line;
>         time_last_line_switch = millis();
>     }
> ```
</details>

remove?
___
*[src/tower_arduino_ide/tower_globals.c, line 198 at r1](https://reviewable.io/reviews/waterloo-rocketry/rlcs/27#-MTcJqjB2elIEL8MWIfE:-MegdGpG2bH09QAFGNlX:b8us65d) ([raw file](https://github.com/waterloo-rocketry/rlcs/blob/366d4ac3a7416f742d8258d0f21fadedc78d1280/src/tower_arduino_ide/tower_globals.c#L198)):*
<details><summary><i>Previously, zx100x100 (Zachariah Mears) wrote…</i></summary><blockquote>

I believe this is me talking about run tank valve (AKA vent valve), no reason to keep this todo
</blockquote></details>

What does this comment refer to? Should it still be here?
___
*[src/tower_arduino_ide/tower_globals.c, line 217 at r3](https://reviewable.io/reviews/waterloo-rocketry/rlcs/27#-MegdOUYC2R_GHKdDxm9:-MegdOUYC2R_GHKdDxmA:bt9dhj7) ([raw file](https://github.com/waterloo-rocketry/rlcs/blob/029c859e6b7193078c29e50c4111d41cf9060d00/src/tower_arduino_ide/tower_globals.c#L217)):*
> ```
>     //close
>     requested->valve_1 = 0;
> ```
instead of the comments, can you create an enum with `VALVE_OPEN` and `VALVE_CLOSED`?

**Review by QuantumManiac — CHANGES_REQUESTED** [review]
> Reviewed 8 of 21 files at r1, 6 of 11 files at r2, 8 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/rlcs/27)* status: all files reviewed, 7 unresolved discussions (waiting on @AidanHa, @Chrisc110, @dwkletke, @jacobdeery, @JaredWatson, @wendi-yu, @ZTeper, and @zx100x100)

___
*[src/tower_arduino_ide/tower_arduino_ide.ino, line 3 at r4](https://reviewable.io/reviews/waterloo-rocketry/rlcs/27#-MkxughR2uYkFg1t5VVj:-MkxughR2uYkFg1t5VVk:b4y1kii) ([raw file](https://github.com/waterloo-rocketry/rlcs/blob/37d02f31c83012d72b3f58824685fa3fa42c7f18/src/tower_arduino_ide/tower_arduino_ide.ino#L3)):*
> ```
> idamet
> ```
diameter

**Review by QuantumManiac — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/rlcs/27)* status: 20 of 24 files reviewed, 6 unresolved discussions (waiting on @AidanHa, @BluCodeGH, @Chrisc110, @dwkletke, @jacobdeery, @JaredWatson, @QuantumManiac, @wendi-yu, and @ZTeper)

___
*[src/client_arduino_ide/client_globals.c, line 23 at r3](https://reviewable.io/reviews/waterloo-rocketry/rlcs/27#-MegcUSA-Qdk8jHcO2MO:-MlRqLtC9FUbLJd3dCBF:bb7f2mf) ([raw file](https://github.com/waterloo-rocketry/rlcs/blob/029c859e6b7193078c29e50c4111d41cf9060d00/src/client_arduino_ide/client_globals.c#L23)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
>     //.linac_lsw_extend = 0,
>     //.linac_lsw_retract = 0
> ```
remove
</blockquote></details>

done
___
*[src/client_arduino_ide/LCD.cpp, line 97 at r3](https://reviewable.io/reviews/waterloo-rocketry/rlcs/27#-MegeUdq5KghzqIFsiAC:-MlRqWH6CxKQSTNfyw1d:bb7f2mf) ([raw file](https://github.com/waterloo-rocketry/rlcs/blob/029c859e6b7193078c29e50c4111d41cf9060d00/src/client_arduino_ide/LCD.cpp#L97)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
>     if (millis() - time_last_line_switch > 2000) {
>         display_first_line = !display_first_line;
>         time_last_line_switch = millis();
>     }
> ```
remove?
</blockquote></details>

done
___
*[src/tower_arduino_ide/tower_arduino_ide.ino, line 3 at r4](https://reviewable.io/reviews/waterloo-rocketry/rlcs/27#-MkxughR2uYkFg1t5VVj:-MlRqc8_7H7gRx3hgbhd:bb7f2mf) ([raw file](https://github.com/waterloo-rocketry/rlcs/blob/37d02f31c83012d72b3f58824685fa3fa42c7f18/src/tower_arduino_ide/tower_arduino_ide.ino#L3)):*
<details><summary><i>Previously, QuantumManiac (Chamath Wijesekera) wrote…</i></summary><blockquote>

> ```
> idamet
> ```
diameter
</blockquote></details>

done
___
*[src/tower_arduino_ide/tower_globals.c, line 198 at r1](https://reviewable.io/reviews/waterloo-rocketry/rlcs/27#-MTcJqjB2elIEL8MWIfE:-MlRqomlE3fDQG6gu-IB:b-1y8dol) ([raw file](https://github.com/waterloo-rocketry/rlcs/blob/366d4ac3a7416f742d8258d0f21fadedc78d1280/src/tower_arduino_ide/tower_globals.c#L198)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

What does this comment refer to? Should it still be here?
</blockquote></details>

probably not. removed.

**Review by BluCodeGH — APPROVED** [review]
:lgtm: let's finally get this in.

> Reviewed 2 of 2 files at r6.
> Dismissed @jacobdeery from 6 discussions.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/rlcs/27#-:-Mo1hcnr2nkyW16cAvVK:b-7ibqy2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Chrisc110, @dwkletke, @JaredWatson, @wendi-yu, and @ZTeper)

___
*[src/tower_arduino_ide/tower_globals.c, line 207 at r6](https://reviewable.io/reviews/waterloo-rocketry/rlcs/27#-Mo1hn_oEYAIE0YFlFHG:-Mo1hn_oEYAIE0YFlFHH:b-fyu7rr) ([raw file](https://github.com/waterloo-rocketry/rlcs/blob/5f65c855e36a40c186edcedeb91c9f6161aa13ea/src/tower_arduino_ide/tower_globals.c#L207)):*
> ```C
> void goto_safe_mode()
> {
>     enum {CLOSED = 0, OPEN} valve_states;
> ```

This seems a bit weird to me but not enough to stop this over.

**Review by QuantumManiac — APPROVED** [review]
:lgtm:

**Pull request merged**
