### PR TITLE
Towerside Power Board respin

### PR DESCRIPTION
**Pull request by JasonBrave**
Towerside Power Board respin schematics + layout + routing

It has everything required in the project proposal except extra GPIO screw terminal.

- - -
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/rlcs/38)

### CODE REVIEW

**Comment by Rio6** [comment]
Have we been using linear regulator before? It's burning away 7V of voltage difference
圖片

nitpick but don't put junction at wire crossing, makes it easier to distinguish junction vs no junction when zoomed out
圖片

**Review by BluCodeGH — APPROVED** [review]
Functionally LGTM. Rio, that part is actually a COTS buck converter daughter board not an LDO, same as the current design uses.

In terms of beautification I've written about what to look for (along with a bunch of other things to double check re schematics) here: https://uwaterloo.atlassian.net/wiki/spaces/ROCKETRY/pages/42646503921/Schematics. I'd recommend you go through it and make sure everything looks good.

**Review by QuantumManiac — APPROVED** [review]
Functionally LGTM. Agree with Jack's comment above, would be good to pretty it up slightly - e.g bottom-left of schematic is pretty dense and stuff could be moved towards the empty area in the top-left

**Review by BluCodeGH — APPROVED** [review]
Looks good! One thing I notice is that it looks like the 12V test point got deleted. Also in general it's good practice to keep the test points all together in one corner and directly connected to the power symbols so they are easy to find rather than sticking them on wherever. Once that's fixed you should be good to move onto layout!

**Review by QuantumManiac — APPROVED** [review]
LGTM, should be good to move onto layout

**Comment by eliaskountouris** [comment]
Looks good to me, except I'm wondering if we need a pull up resistor on the reset switch. I'm unsure if the Arduino has one already on it.
image

**Comment by JasonBrave** [comment]
Added PCB layout
Note that UART Tx/Rx silkscreen should be swapped

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
Layout looking good, some tweaks I'd make:
1. You could tidy up the horizontal spacing of J4/J5/J6/J7 to make it symmetrical and pretty
2. On the topic of pretty I'm a sucker for rounded corners, up to you if you want to add them.
3. Your 12V test point has gone missing, and you'll want to remove the silkscreen that used to be for the 3V3 testpoint
4. I'd recommend having the 7-segment and the two status LEDs roughly centered with lots of free space around them for silkscreen comments.
5. When you think about someone's perspective when plugging a wire into a screw terminal, typically they'll have the opening of the screw terminal facing them so they can see what they're doing. That means your current silkscreen labels would be upside down from that perspective, so you should flip them around.

**Comment by Joe-Joe-Joe-Joe** [comment]
- R3-10 symbol values are 150 ohm but you have a comment saying they're 100 ohm
- R11 is connected but you have a dangling wire over top of it
That's it, I couldn't run a trace to save my life

**Comment by JasonBrave** [comment]
> * R3-10 symbol values are 150 ohm but you have a comment saying they're 100 ohm
> 
>     * R11 is connected but you have a dangling wire over top of it
>       That's it, I couldn't run a trace to save my life

Is this for schematic?
I think the the comment of R3-R10 are fixed a while ago
I did not find a dangling wire around R11

**Comment by Joe-Joe-Joe-Joe** [comment]
Was a uhhhhhhh issue on my end. You can ignore my prior comments.

**Review by BluCodeGH — APPROVED** [review]
Looks great! Feel free to start on routing.

Based on how the board is mounted in RLCS the standard viewing angle is actually upside down compared to how the board is in kicad. So I'd flip the LED silkscreens to be upside down.
Also probably good to add a silkscreen to above the 7-segment saying `Current State`.

**Comment by QuantumManiac** [comment]
> Based on how the board is mounted in RLCS the standard viewing angle is actually upside down compared to how the board is in kicad. So I'd flip the LED silkscreens to be upside down.

Should we rotate all silkscreens to match this then? Having the labels be facing one way and the component refdes facing the other feels a bit odd.

**Comment by JasonBrave** [comment]
Routing done

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
This is looking good! A couple changes to make:

1. Not all traces of the same net need to be the same width. Each trace should be sized to the expected current it needs to carry. For example the 12V trace from the fuse to the 5 pin connects should be big like you have it, but the trace from the fuse to the test point should just be the standard small trace width since it won't see any current. Likewise you should shrink down the trace for the actuator battery (its for voltage measurement only), between the GND pin and the reset button, and between 12V and its voltage sense resistor.
2. Re chamath's comment, I realized that we can actually just rotate the entire board super easily. Make sure "locked items" is ticked in the selection options in the lower right corner, select everything with ctrl+a, and rotate! Make sure to override locked items in the dialogue so that you can change the arduino footprint.
3. Why not stick the team logo in that big open space next to the reset button?
4. Your voltage sense resistors have some daisy-chaining going on, best to avoid having a signal enter and leave a pad since if that pad gets torn then the signal is cut. Here it's not a huge deal (if the pad gets torn then we can't exactly do anything useful with the signal) but its good practice to avoid anyway.
5. Your 12V line also has quite a bit of daisy-chaining, but through through hole pads which is acceptable (it's quite hard to tear off a through hole lol). In the future try to avoid it but no need to reroute in this case.

**Comment by JasonBrave** [comment]
Updated the PCB routing

**Review by BluCodeGH — APPROVED** [review]
LGTM. Let's get some more eyes on this tho, and we'll close the PR when the board is ordered.

**Comment by Rio6** [comment]
圖片

All these 12V connectors have ground trace much thinner than the 12V trace, is this a problem? Same amount of current will have to return from somewhere.

**Comment by rdakhil** [comment]
Looks good to me. Just one comment that isn't too critical:

wouldn't hurt to have the decoupling caps C4 and C3 a little bit closer to the DC switching regulator. the closer the better (as long as it's still hand-solderable of course)
image
maybe something like this? you'll also improve the grounding of your switching regulator this way
image

**Review by rdakhil — APPROVED** [review]

**Comment by BluCodeGH** [comment]
> All these 12V connectors have ground trace much thinner than the 12V trace, is this a problem? Same amount of current will have to return from somewhere.

The thick trace is mostly for passthrough, the peak possible 12v line current is ~300 mA (it drives relay coils, will often be _much_ less) and with such a short trace the width there should be perfectly sufficient.

**Comment by Rio6** [comment]
> > All these 12V connectors have ground trace much thinner than the 12V trace, is this a problem? Same amount of current will have to return from somewhere.
> 
> The thick trace is mostly for passthrough, the peak possible 12v line current is ~300 mA (it drives relay coils, will often be _much_ less) and with such a short trace the width there should be perfectly sufficient.

Even if it's pass through KCL still needs to apply, although I agree it's probably sufficient. Just that having 12V this wide paired with thinner ground makes the wide 12V look a bit extra?

LGTM overall

**Review by QuantumManiac — APPROVED** [review]
Would be good to just go ahead and rotate the entire board 180 degrees as per Jack's comment. Otherwise, LGTM

**Comment by JekkuChen** [comment]
Board has been ordered on JLCPCB. Merging PR.

**Pull request merged**
